kind: pipeline
type: docker
name: Icarus

steps:
  - name: starplex-build
    image: gradle:jdk21
    commands:
      - cd starplex
      - gradle bootJar -x test

  - name: starplex-push
    image: plugins/docker
    depends_on: [ starplex-build ]
    settings:
      registry: registry.icaruspw.dev
      repo: registry.icaruspw.dev/icarus/starplex
      dockerfile: starplex/Dockerfile
      username: icarus
      password:
        from_secret: REGISTRY_PASSWORD
      auto_tag: true
      use_cache: true

  - name: starplex-wbe-build
    image: node:22
    commands:
      - cd starplex-web
      - npm install
      - npm run build

  - name: starplex-web-push
    image: plugins/docker
    depends_on: [ starplex-wbe-build ]
    settings:
      registry: registry.icaruspw.dev
      repo: registry.icaruspw.dev/icarus/starplex-web
      dockerfile: starplex-web/Dockerfile
      username: icarus
      password:
        from_secret: REGISTRY_PASSWORD
      auto_tag: true
      use_cache: true

  - name: ceres-build
    image: golang:1.23.2-alpine3.20
    commands:
      - cd ceres
      - go build -o ceres .

  - name: ceres-push
    image: plugins/docker
    depends_on: [ ceres-build ]
    settings:
      registry: registry.icaruspw.dev
      repo: registry.icaruspw.dev/icarus/ceres
      dockerfile: ceres/Dockerfile
      username: icarus
      password:
        from_secret: REGISTRY_PASSWORD
      auto_tag: true
      use_cache: true
  
  - name: ceres-web-build
    image: node:22
    commands:
      - cd ceres-web
      - npm install
      - npm run build

  - name: ceres-web-push
    image: plugins/docker
    depends_on: [ starplex-wbe-build ]
    settings:
      registry: registry.icaruspw.dev
      repo: registry.icaruspw.dev/icarus/ceres-web
      dockerfile: ceres-web/Dockerfile
      username: icarus
      password:
        from_secret: REGISTRY_PASSWORD
      auto_tag: true
      use_cache: true

  - name: iris-build
    image: rust:1.82.0-bookworm
    depends_on: [ starplex-push, starplex-web-push, ceres-push, ceres-web-push ]
    commands:
      - cd iris
      - cargo build --release

  - name: aurora-build
    image: rust:1.82.0-bookworm
    depends_on: [ iris-build ]
    commands:
      - cd aurora
      - cargo build --release
