ip = "0.0.0.0"
port = 10000
id = "aurora"
endpoint = "http://127.0.0.1:10000/cluster"
secret = "ce38ee76-b0ee-dcf3-d4f6-641a12d951dc"
nodes = [
    { id = "aurora-0", endpoint = "http://127.0.0.1:10000/cluster" },
    { id = "aurora-1", endpoint = "http://127.0.0.1:10001/cluster" },
    { id = "aurora-2", endpoint = "http://127.0.0.1:10002/cluster" },
]